# Generated by Django 3.0.3 on 2020-03-04 03:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('surname', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs')], default='Mr', max_length=10)),
                ('ename', models.CharField(max_length=30)),
                ('empid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('empdetails', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField(default=datetime.datetime(2020, 3, 4, 9, 2, 19, 946514))),
                ('checkout', models.DateTimeField(default=None)),
                ('ename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.Employee')),
            ],
        ),
    ]
