# Generated by Django 3.0.3 on 2020-03-04 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_auto_20200304_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emptime',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 9, 11, 6, 114474)),
        ),
        migrations.AlterField(
            model_name='emptime',
            name='checkout',
            field=models.DateTimeField(blank=True),
        ),
    ]
