# Generated by Django 3.0.3 on 2020-03-04 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_auto_20200304_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emptime',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 9, 12, 57, 752719)),
        ),
        migrations.AlterField(
            model_name='emptime',
            name='checkout',
            field=models.DateTimeField(null=True),
        ),
    ]
