# Generated by Django 3.0.3 on 2020-03-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_auto_20200304_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emptime',
            name='checkin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='emptime',
            name='checkout',
            field=models.DateTimeField(),
        ),
    ]
